# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rodrigobsilva
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  architecture: arm64
  runtime: nodejs22.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SECRET_KEY: ${env:SECRET_KEY}
    BUCKET_NAME: !Ref UploadsBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - s3:PutObject
          Resource: !Sub '${UploadsBucket.Arn}/*'

package: 
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
      handler: src/functions/signup.handler
      events:
      - httpApi:
          path: /signup
          method: POST
  
  me:
      handler: src/functions/me.handler
      events:
      - httpApi:
          path: /me
          method: GET
  
  createMeal:
      handler: src/functions/create-meal.handler
      events:
      - httpApi:
          path: /meals
          method: POST

  listMeals:
      handler: src/functions/list-meals.handler
      events:
      - httpApi:
          path: /meals
          method: GET

  getMealById:
      handler: src/functions/get-meal-by-id.handler
      events:
      - httpApi:
          path: /meals/{mealId}
          method: GET

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-jstack-foodiary